/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemaker.apps.mobile.fingenie.fingenie.Offer;
import com.wavemaker.apps.mobile.fingenie.fingenie.OfferFeedback;

/**
 * Service object for domain model class {@link Offer}.
 */
public interface OfferService {

    /**
     * Creates a new Offer. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Offer if any.
     *
     * @param offer Details of the Offer to be created; value cannot be null.
     * @return The newly created Offer.
     */
	Offer create(Offer offer);


	/**
	 * Returns Offer by given id if exists.
	 *
	 * @param offerIdInstance The id of the Offer to get; value cannot be null.
	 * @return Offer associated with the given offerIdInstance.
     * @throws EntityNotFoundException If no Offer is found.
	 */
	Offer getById(Integer offerIdInstance) throws EntityNotFoundException;

    /**
	 * Find and return the Offer by given id if exists, returns null otherwise.
	 *
	 * @param offerIdInstance The id of the Offer to get; value cannot be null.
	 * @return Offer associated with the given offerIdInstance.
	 */
	Offer findById(Integer offerIdInstance);


	/**
	 * Updates the details of an existing Offer. It replaces all fields of the existing Offer with the given offer.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Offer if any.
     *
	 * @param offer The details of the Offer to be updated; value cannot be null.
	 * @return The updated Offer.
	 * @throws EntityNotFoundException if no Offer is found with given input.
	 */
	Offer update(Offer offer) throws EntityNotFoundException;

    /**
	 * Deletes an existing Offer with the given id.
	 *
	 * @param offerIdInstance The id of the Offer to be deleted; value cannot be null.
	 * @return The deleted Offer.
	 * @throws EntityNotFoundException if no Offer found with the given id.
	 */
	Offer delete(Integer offerIdInstance) throws EntityNotFoundException;

	/**
	 * Find all Offers matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Offers.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Offer> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Offers matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Offers.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Offer> findAll(String query, Pageable pageable);

    /**
	 * Exports all Offers matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Offers in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Offer.
	 */
	long count(String query);

    /*
     * Returns the associated offerFeedbacks for given Offer id.
     *
     * @param offerId value of offerId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated OfferFeedback instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<OfferFeedback> findAssociatedOfferFeedbacks(Integer offerId, Pageable pageable);

}

