/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemaker.apps.mobile.fingenie.fingenie.Offer;
import com.wavemaker.apps.mobile.fingenie.fingenie.OfferType;

/**
 * Service object for domain model class {@link OfferType}.
 */
public interface OfferTypeService {

    /**
     * Creates a new OfferType. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on OfferType if any.
     *
     * @param offerTypeInstance Details of the OfferType to be created; value cannot be null.
     * @return The newly created OfferType.
     */
	OfferType create(OfferType offerTypeInstance);


	/**
	 * Returns OfferType by given id if exists.
	 *
	 * @param offertypeId The id of the OfferType to get; value cannot be null.
	 * @return OfferType associated with the given offertypeId.
     * @throws EntityNotFoundException If no OfferType is found.
	 */
	OfferType getById(Integer offertypeId) throws EntityNotFoundException;

    /**
	 * Find and return the OfferType by given id if exists, returns null otherwise.
	 *
	 * @param offertypeId The id of the OfferType to get; value cannot be null.
	 * @return OfferType associated with the given offertypeId.
	 */
	OfferType findById(Integer offertypeId);


	/**
	 * Updates the details of an existing OfferType. It replaces all fields of the existing OfferType with the given offerTypeInstance.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on OfferType if any.
     *
	 * @param offerTypeInstance The details of the OfferType to be updated; value cannot be null.
	 * @return The updated OfferType.
	 * @throws EntityNotFoundException if no OfferType is found with given input.
	 */
	OfferType update(OfferType offerTypeInstance) throws EntityNotFoundException;

    /**
	 * Deletes an existing OfferType with the given id.
	 *
	 * @param offertypeId The id of the OfferType to be deleted; value cannot be null.
	 * @return The deleted OfferType.
	 * @throws EntityNotFoundException if no OfferType found with the given id.
	 */
	OfferType delete(Integer offertypeId) throws EntityNotFoundException;

	/**
	 * Find all OfferTypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OfferTypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<OfferType> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all OfferTypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OfferTypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<OfferType> findAll(String query, Pageable pageable);

    /**
	 * Exports all OfferTypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the OfferTypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the OfferType.
	 */
	long count(String query);

    /*
     * Returns the associated offers for given OfferType id.
     *
     * @param offerTypeId value of offerTypeId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Offer instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Offer> findAssociatedOffers(Integer offerTypeId, Pageable pageable);

}

