/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemaker.apps.mobile.fingenie.fingenie.OfferFeedback;

/**
 * Service object for domain model class {@link OfferFeedback}.
 */
public interface OfferFeedbackService {

    /**
     * Creates a new OfferFeedback. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on OfferFeedback if any.
     *
     * @param offerFeedback Details of the OfferFeedback to be created; value cannot be null.
     * @return The newly created OfferFeedback.
     */
	OfferFeedback create(OfferFeedback offerFeedback);


	/**
	 * Returns OfferFeedback by given id if exists.
	 *
	 * @param offerfeedbackId The id of the OfferFeedback to get; value cannot be null.
	 * @return OfferFeedback associated with the given offerfeedbackId.
     * @throws EntityNotFoundException If no OfferFeedback is found.
	 */
	OfferFeedback getById(Integer offerfeedbackId) throws EntityNotFoundException;

    /**
	 * Find and return the OfferFeedback by given id if exists, returns null otherwise.
	 *
	 * @param offerfeedbackId The id of the OfferFeedback to get; value cannot be null.
	 * @return OfferFeedback associated with the given offerfeedbackId.
	 */
	OfferFeedback findById(Integer offerfeedbackId);


	/**
	 * Updates the details of an existing OfferFeedback. It replaces all fields of the existing OfferFeedback with the given offerFeedback.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on OfferFeedback if any.
     *
	 * @param offerFeedback The details of the OfferFeedback to be updated; value cannot be null.
	 * @return The updated OfferFeedback.
	 * @throws EntityNotFoundException if no OfferFeedback is found with given input.
	 */
	OfferFeedback update(OfferFeedback offerFeedback) throws EntityNotFoundException;

    /**
	 * Deletes an existing OfferFeedback with the given id.
	 *
	 * @param offerfeedbackId The id of the OfferFeedback to be deleted; value cannot be null.
	 * @return The deleted OfferFeedback.
	 * @throws EntityNotFoundException if no OfferFeedback found with the given id.
	 */
	OfferFeedback delete(Integer offerfeedbackId) throws EntityNotFoundException;

	/**
	 * Find all OfferFeedbacks matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OfferFeedbacks.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<OfferFeedback> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all OfferFeedbacks matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OfferFeedbacks.
     *
     * @see Pageable
     * @see Page
	 */
    Page<OfferFeedback> findAll(String query, Pageable pageable);

    /**
	 * Exports all OfferFeedbacks matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the OfferFeedbacks in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the OfferFeedback.
	 */
	long count(String query);


}

