/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.apps.mobile.fingenie.fingenie.OfferFeedback;
import com.wavemaker.apps.mobile.fingenie.fingenie.service.OfferFeedbackService;

/**
 * Controller object for domain model class OfferFeedback.
 * @see OfferFeedback
 */
@RestController("FinGenie.OfferFeedbackController")
@Api(value = "OfferFeedbackController", description = "Exposes APIs to work with OfferFeedback resource.")
@RequestMapping("/FinGenie/OfferFeedback")
public class OfferFeedbackController {

    private static final Logger LOGGER = LoggerFactory.getLogger(OfferFeedbackController.class);

    @Autowired
    @Qualifier("FinGenie.OfferFeedbackService")
    private OfferFeedbackService offerFeedbackService;

    @ApiOperation(value = "Creates a new OfferFeedback instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public OfferFeedback createOfferFeedback(@RequestBody OfferFeedback offerFeedback) {
        LOGGER.debug("Create OfferFeedback with information: {}", offerFeedback);
        offerFeedback = offerFeedbackService.create(offerFeedback);
        LOGGER.debug("Created OfferFeedback with information: {}", offerFeedback);
        return offerFeedback;
    }

    @ApiOperation(value = "Returns the OfferFeedback instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public OfferFeedback getOfferFeedback(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting OfferFeedback with id: {}", id);
        OfferFeedback foundOfferFeedback = offerFeedbackService.getById(id);
        LOGGER.debug("OfferFeedback details with id: {}", foundOfferFeedback);
        return foundOfferFeedback;
    }

    @ApiOperation(value = "Updates the OfferFeedback instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public OfferFeedback editOfferFeedback(@PathVariable("id") Integer id, @RequestBody OfferFeedback offerFeedback) throws EntityNotFoundException {
        LOGGER.debug("Editing OfferFeedback with id: {}", offerFeedback.getOfferFeedbackId());
        offerFeedback.setOfferFeedbackId(id);
        offerFeedback = offerFeedbackService.update(offerFeedback);
        LOGGER.debug("OfferFeedback details with id: {}", offerFeedback);
        return offerFeedback;
    }

    @ApiOperation(value = "Deletes the OfferFeedback instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteOfferFeedback(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting OfferFeedback with id: {}", id);
        OfferFeedback deletedOfferFeedback = offerFeedbackService.delete(id);
        return deletedOfferFeedback != null;
    }

    /**
     * @deprecated Use {@link #findOfferFeedbacks(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of OfferFeedback instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<OfferFeedback> findOfferFeedbacks(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering OfferFeedbacks list");
        return offerFeedbackService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the list of OfferFeedback instances matching the search criteria.")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<OfferFeedback> findOfferFeedbacks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering OfferFeedbacks list");
        return offerFeedbackService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportOfferFeedbacks(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return offerFeedbackService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns the total count of OfferFeedback instances.")
    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Long countOfferFeedbacks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting OfferFeedbacks");
        return offerFeedbackService.count(query);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service OfferFeedbackService instance
	 */
    protected void setOfferFeedbackService(OfferFeedbackService service) {
        this.offerFeedbackService = service;
    }
}
