/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.apps.mobile.fingenie.fingenie.Offer;
import com.wavemaker.apps.mobile.fingenie.fingenie.OfferFeedback;
import com.wavemaker.apps.mobile.fingenie.fingenie.service.OfferService;

/**
 * Controller object for domain model class Offer.
 * @see Offer
 */
@RestController("FinGenie.OfferController")
@Api(value = "OfferController", description = "Exposes APIs to work with Offer resource.")
@RequestMapping("/FinGenie/Offer")
public class OfferController {

    private static final Logger LOGGER = LoggerFactory.getLogger(OfferController.class);

    @Autowired
    @Qualifier("FinGenie.OfferService")
    private OfferService offerService;

    @ApiOperation(value = "Creates a new Offer instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Offer createOffer(@RequestBody Offer offer) {
        LOGGER.debug("Create Offer with information: {}", offer);
        offer = offerService.create(offer);
        LOGGER.debug("Created Offer with information: {}", offer);
        return offer;
    }

    @ApiOperation(value = "Returns the Offer instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Offer getOffer(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Offer with id: {}", id);
        Offer foundOffer = offerService.getById(id);
        LOGGER.debug("Offer details with id: {}", foundOffer);
        return foundOffer;
    }

    @ApiOperation(value = "Updates the Offer instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Offer editOffer(@PathVariable("id") Integer id, @RequestBody Offer offer) throws EntityNotFoundException {
        LOGGER.debug("Editing Offer with id: {}", offer.getOfferId());
        offer.setOfferId(id);
        offer = offerService.update(offer);
        LOGGER.debug("Offer details with id: {}", offer);
        return offer;
    }

    @ApiOperation(value = "Deletes the Offer instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteOffer(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Offer with id: {}", id);
        Offer deletedOffer = offerService.delete(id);
        return deletedOffer != null;
    }

    /**
     * @deprecated Use {@link #findOffers(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Offer instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Offer> findOffers(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Offers list");
        return offerService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the list of Offer instances matching the search criteria.")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Offer> findOffers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Offers list");
        return offerService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportOffers(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return offerService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns the total count of Offer instances.")
    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Long countOffers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting Offers");
        return offerService.count(query);
    }

    @RequestMapping(value = "/{id:.+}/offerFeedbacks", method = RequestMethod.GET)
    @ApiOperation(value = "Gets the offerFeedbacks instance associated with the given id.")
    public Page<OfferFeedback> findAssociatedOfferFeedbacks(@PathVariable("id") Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated offerFeedbacks");
        return offerService.findAssociatedOfferFeedbacks(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service OfferService instance
	 */
    protected void setOfferService(OfferService service) {
        this.offerService = service;
    }
}
