/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * Offer generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`OFFER`")
public class Offer implements Serializable {

    private Integer offerId;
    private Integer offerTypeId;
    private Float minInt;
    private Integer amount;
    private Integer tenure;
    private Integer rating;
    private Integer bankId;
    private String originationFee;
    private Boolean prePaymentPenalty;
    private Integer annualFee;
    private Float downpayment;
    private Boolean offerActive;
    @Type(type = "DateTime")
    private LocalDateTime offerEndDate;
    @Type(type = "DateTime")
    private LocalDateTime offerStartDate;
    private List<OfferFeedback> offerFeedbacks = new ArrayList<>();
    private Bank bank;
    private OfferType offerType;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`OFFER_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getOfferId() {
        return this.offerId;
    }

    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    @Column(name = "`OFFER_TYPE_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getOfferTypeId() {
        return this.offerTypeId;
    }

    public void setOfferTypeId(Integer offerTypeId) {
        this.offerTypeId = offerTypeId;
    }

    @Column(name = "`MIN_INT`", nullable = true, scale = 0, precision = 10)
    public Float getMinInt() {
        return this.minInt;
    }

    public void setMinInt(Float minInt) {
        this.minInt = minInt;
    }

    @Column(name = "`AMOUNT`", nullable = true, scale = 0, precision = 10)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name = "`TENURE`", nullable = true, scale = 0, precision = 10)
    public Integer getTenure() {
        return this.tenure;
    }

    public void setTenure(Integer tenure) {
        this.tenure = tenure;
    }

    @Column(name = "`RATING`", nullable = true, scale = 0, precision = 10)
    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Column(name = "`BANK_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getBankId() {
        return this.bankId;
    }

    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    @Column(name = "`ORIGINATION_FEE`", nullable = true, length = 255)
    public String getOriginationFee() {
        return this.originationFee;
    }

    public void setOriginationFee(String originationFee) {
        this.originationFee = originationFee;
    }

    @Column(name = "`PRE_PAYMENT_PENALTY`", nullable = true)
    public Boolean getPrePaymentPenalty() {
        return this.prePaymentPenalty;
    }

    public void setPrePaymentPenalty(Boolean prePaymentPenalty) {
        this.prePaymentPenalty = prePaymentPenalty;
    }

    @Column(name = "`ANNUAL FEE`", nullable = true, scale = 0, precision = 10)
    public Integer getAnnualFee() {
        return this.annualFee;
    }

    public void setAnnualFee(Integer annualFee) {
        this.annualFee = annualFee;
    }

    @Column(name = "`DOWNPAYMENT`", nullable = true, scale = 0, precision = 10)
    public Float getDownpayment() {
        return this.downpayment;
    }

    public void setDownpayment(Float downpayment) {
        this.downpayment = downpayment;
    }

    @Column(name = "`OFFER_ACTIVE`", nullable = true)
    public Boolean getOfferActive() {
        return this.offerActive;
    }

    public void setOfferActive(Boolean offerActive) {
        this.offerActive = offerActive;
    }

    @Column(name = "`OFFER_END_DATE`", nullable = true)
    public LocalDateTime getOfferEndDate() {
        return this.offerEndDate;
    }

    public void setOfferEndDate(LocalDateTime offerEndDate) {
        this.offerEndDate = offerEndDate;
    }

    @Column(name = "`OFFER_START_DATE`", nullable = true)
    public LocalDateTime getOfferStartDate() {
        return this.offerStartDate;
    }

    public void setOfferStartDate(LocalDateTime offerStartDate) {
        this.offerStartDate = offerStartDate;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "offer")
    public List<OfferFeedback> getOfferFeedbacks() {
        return this.offerFeedbacks;
    }

    public void setOfferFeedbacks(List<OfferFeedback> offerFeedbacks) {
        this.offerFeedbacks = offerFeedbacks;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`BANK_ID`", referencedColumnName = "`BANK_ID`", insertable = false, updatable = false)
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        if(bank != null) {
            this.bankId = bank.getBankId();
        }

        this.bank = bank;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`OFFER_TYPE_ID`", referencedColumnName = "`OFFER_TYPE_ID`", insertable = false, updatable = false)
    public OfferType getOfferType() {
        return this.offerType;
    }

    public void setOfferType(OfferType offerType) {
        if(offerType != null) {
            this.offerTypeId = offerType.getOfferTypeId();
        }

        this.offerType = offerType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Offer)) return false;
        final Offer offer = (Offer) o;
        return Objects.equals(getOfferId(), offer.getOfferId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOfferId());
    }
}

