/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.wavemaker.apps.mobile.fingenie.fingenie;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OfferFeedback generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`OFFER_FEEDBACK`")
public class OfferFeedback implements Serializable {

    private Integer offerFeedbackId;
    private Integer offerId;
    private Integer userId;
    private Integer rating;
    private String feedback;
    private Offer offer;
    private Users users;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`OFFER_FEEDBACK_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getOfferFeedbackId() {
        return this.offerFeedbackId;
    }

    public void setOfferFeedbackId(Integer offerFeedbackId) {
        this.offerFeedbackId = offerFeedbackId;
    }

    @Column(name = "`OFFER_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getOfferId() {
        return this.offerId;
    }

    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    @Column(name = "`USER_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "`RATING`", nullable = true, scale = 0, precision = 10)
    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Column(name = "`FEEDBACK`", nullable = true, length = 255)
    public String getFeedback() {
        return this.feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`OFFER_ID`", referencedColumnName = "`OFFER_ID`", insertable = false, updatable = false)
    public Offer getOffer() {
        return this.offer;
    }

    public void setOffer(Offer offer) {
        if(offer != null) {
            this.offerId = offer.getOfferId();
        }

        this.offer = offer;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`USER_ID`", referencedColumnName = "`USER_ID`", insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        if(users != null) {
            this.userId = users.getUserId();
        }

        this.users = users;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof OfferFeedback)) return false;
        final OfferFeedback offerFeedback = (OfferFeedback) o;
        return Objects.equals(getOfferFeedbackId(), offerFeedback.getOfferFeedbackId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOfferFeedbackId());
    }
}

